name: "en_to_kin_transformer"

data:
    train: "data/train"
    dev:   "data/dev"
    test:  "data/test"
    level: "bpe"
    sample_train_subset: -1             # Extend to longer sentences.
    sample_dev_subset: -1
    dataset_type: "plain"
    src:
        lang: "en"
        max_length: 30
        min_length: 1
        lowercase: False
        normalize: False
        level: "bpe"
        voc_limit: 400
        voc_min_freq: 1
        # voc_file: "data/vocab.en"
        tokenizer_type: "subword-nmt"
        tokenizer_cfg:
            num_merges: 200
            codes: "bpe.4000.codes"
            dropout: 0.0
            pretokenizer: "none"
    trg:
        lang: "kin"
        max_length: 30
        min_length: 1
        lowercase: False
        normalize: False
        level: "bpe"
        voc_limit: 400
        voc_min_freq: 1
        # voc_file: "data/vocab.kin"
        tokenizer_type: "subword-nmt"
        tokenizer_cfg:
            num_merges: 200
            codes: "bpe.4000.codes"
            dropout: 0.0
            pretokenizer: "none"

testing:
    beam_size: 5
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.999]
    scheduling: "plateau"
    patience: 5
    learning_rate_factor: 0.5
    learning_rate_warmup: 1000
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0003
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_size: 4096
    batch_type: "token"
    eval_batch_size: 3600
    eval_batch_type: "token"
    batch_multiplier: 1
    early_stopping_metric: "ppl"
    epochs: 5
    validation_freq: 1000
    eval_metric: "bleu"
    model_dir: "models/en_to_kin_transformer"
    overwrite: True
    shuffle: True
    use_cuda: False
    fp16: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2, 3]
    keep_last_ckpts: 3

model:
    initializer: "xavier"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    tied_embeddings: False
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4             
        embeddings:
            embedding_dim: 256   
            scale: True
            dropout: 0.2
        hidden_size: 256         
        ff_size: 1024            
        dropout: 0.3
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4             
        embeddings:
            embedding_dim: 256   
            scale: True
            dropout: 0.2
        hidden_size: 256         
        ff_size: 1024            
        dropout: 0.3